apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-jobmanager
  template:
    metadata:
      labels:
        app: flink-jobmanager
    spec:
      containers:
        - name: jobmanager
          image: ghcr.io/lee-dongwook/signalflow/flink-jobs:latest
          args: ["jobmanager"]
          ports:
            - containerPort: 8081
              name: ui
            - containerPort: 6123
              name: rpc
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "flink-jobmanager"
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: flink
spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: ui
    - port: 6123
      name: rpc
  selector:
    app: flink-jobmanager
