global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Flink Job Manager / TaskManager Metrics
  - job_name: "flink"
    static_configs:
      - targets: ["flink-jobmanager:9250", "flink-taskmanager: 9250"]

  # Kafka Broker/Consumer
  - job_name: "Kafka"
    static_configs:
      - targets: ["kafka:9308"]

  # ClickHouse
  - job_name: "clickhouse"
    static_configs:
      -targets: ["clickhouse:8001"]
