name: "intelligence_lakehouse_dbt"
version: "1.0.0"
config-version: 2

profile: "spark_iceberg"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  intelligence_lakehouse_dbt:
    marts:
      +materialized: table
      +file_format: iceberg
